plugins {
    id "com.android.application"
}

android {
    namespace "io.github.audienceofone.djcontrol"
    compileSdk 35

    defaultConfig {
        applicationId "io.github.audienceofone.djcontrol"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "0.2.0"

        buildConfigField "String", "PROVENANCE", '"audience-of-one:kcg:2026"'
    }

    buildFeatures {
        buildConfig true
    }
}
